plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rescue.gpsapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.rescue.gpsapp"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
}
